identifier: pardakht
description: The secure and user-friendly payment app. Easily send/receive money, pay for goods/services, and track spending. Simplify your finances with Pardakht.
org: net.pardakht
template: app
path: ''
gen_app: true
get_deps: true
gen_states: true
gen_blocs: true
gen_gateway: true
gen_adapters: true
gen_main: true
gen_views: true
version: ''
dependencies:
- flutter_bloc
- shared_preferences
- go_router
- file_picker
- file_saver
- kooza_flutter
- flutter_bloc
- device_preview
- easy_localization
dev_dependencies:
- bloc_test
- mockito
enums:
- identifier: UserRole
  fields:
  - admin
  - customer
  default: customer
  path: lib/src/domain/enums
- identifier: ProductType
  fields:
  - classic
  - modern
  default: modern
  path: lib/src/domain/enums
entities:
- identifier: User
  is_abstract: false
  is_immutable: true
  gen_blocs: true
  gen_states: true
  has_serializers: true
  path: lib/src/domain/entities
  imports:
  - ../enums/user_role.dart
  fields:
  - identifier: id
    data_type: String
    default: null
    documentation: null
    is_enum: false
    is_immutable: true
    is_nullable: true
    is_public: true
  - identifier: name
    data_type: String
    default: null
    documentation: null
    is_enum: false
    is_immutable: true
    is_nullable: true
    is_public: true
  - identifier: email
    data_type: String
    default: null
    documentation: null
    is_enum: false
    is_immutable: true
    is_nullable: true
    is_public: true
  - identifier: password
    data_type: String
    default: null
    documentation: null
    is_enum: false
    is_immutable: true
    is_nullable: true
    is_public: true
  - identifier: role
    data_type: UserRole
    default: UserRole.admin
    documentation: null
    is_enum: true
    is_immutable: true
    is_nullable: false
    is_public: true
  constructors:
  - identifier: null
    is_private: false
    are_params_named: true
    init_defaults: false
  - identifier: init
    is_private: false
    are_params_named: true
    init_defaults: true